### ISSUE TITLE
How to get stride from WicBitmapSource

### ISSUE THREAD

**Issue by Bxaa** [smourier/WicNet#1]
How to get stride of WicBitmapSource?

**Comment by smourier** [comment]
Hi,

This should work:

```
using (var bmp = WicBitmapSource.Load("SamsungSGH-P270.jpg"))
{
    var bpp = bmp.WicPixelFormat.BitsPerPixel;
    var stride = bpp * bmp.Width / 8;
    Console.WriteLine(stride);
}

```
Or, depending on how you got the bitmap in the first place, you can lock it and ask for the stride, e.g. :

```
membmp.WithLock(WICBitmapLockFlags.WICBitmapLockRead, l =>
{
    Console.WriteLine(l.Stride);
});

```

Since it's useful, I've checked in it as a property of WicBitmapSource: https://github.com/smourier/WicNet/commit/66701c8d05ebe6334de753e0d73f9aa5cf9c19cc

**Comment by Bxaa** [comment]
Thx, very useful

**Comment by Bxaa** [comment]
(Offtop)

AOT WicNet.dll Common Language Runtime detected an invalid program. The body of method 'Void ComFactory..ctor()' is invalid
Maybe as an author you can help me with this?
I can't figure out what's wrong.

My bug report:
https://github.com/dotnet/runtimelab/issues/1935

Code sample for reproduce:
https://drive.google.com/file/d/1Mw2gPtAdYR8dWpyj5nUu9KgxTlTKTtoV/view?usp=sharing

Just publish and you will get native exe in ...Wic_Test\bin\x64\Release\net6.0-windows\win-x64\native
Test it

**Comment by smourier** [comment]
ComFactory is a class that is defined like this:

```
[ComImport, Guid("CACAF262-9370-4615-A13B-9F5539DA4C0A")]
private class ComFactory
{
}
```

Which defines a COM coclass with a guid. Apparently, AOT doesn't support this. Even if you change for this:

`Activator.CreateInstance(Type.GetTypeFromCLSID(new Guid("CACAF262-9370-4615-A13B-9F5539DA4C0A")));`

It will fail later on with a "_Fail: Operation is not supported on this platform._"

I think this is expected since AOT doesn't support COM (or only partially) as stated here: [Limitations of Native AOT deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/native-aot#limitations-of-native-aot-deployment):

> Native AOT applications comes with a few fundamental limitations and compatibility issues. The key limitations include
> ... No built-in COM (only applies to Windows) ...

PS: Please don't ask more than one question per issue.
