### ISSUE TITLE
How to pass `System.Windows.Media.Imaging.BitmapSource` to `WicBitmapSource.FromSource()`

### ISSUE THREAD

**Issue by d2phap** [smourier/WicNet#2]
Hi, I'm playing around with this library on .NET 6
I use Magick.NET to read the image, then convert it to `System.Windows.Media.Imaging.BitmapSource`.

```cs
using var imgM = new MagickImage("photo.png");
System.Windows.Media.Imaging.BitmapSource src = imgM.ToBitmapSource();


using var bmp = WicBitmapSource.FromSource(src); // ERROR!

```

![image](https://user-images.githubusercontent.com/3154213/180764194-22cb0386-0233-45f1-a0fa-8092073fd98c.png)

Is there any way to convert `System.Windows.Media.Imaging.BitmapSource` to `WicNet.WicBitmapSource`?

**Comment by d2phap** [comment]
Also, I tried to use `WicBitmapSource.FromMemory()` method because Magick.NET can return byte array, but I had the error "The buffer allocated is insufficient" when passing stride value.
I guess my calculation is not correct.

```cs
using var imgM = new MagickImage("photo.png");
byte[] bytes = imgM.ToByteArray();
var stride = ((imgM.Width * 32 + 31) & ~31) / 8;
        
using var bmp = WicBitmapSource.FromMemory(
  imgM.Width,
  imgM.Height,
  WicPixelFormat.GUID_WICPixelFormat32bppPRGBA,
  stride,
  bytes);
```

**Comment by smourier** [comment]
To convert a WPF BitmapSource to a WicNet's WicBitmapSource, you can use this function:

```
public static WicBitmapSource FromBitmapSource(BitmapSource bmp)
{
    if (bmp == null)
        return null;

    var handle = (SafeHandleZeroOrMinusOneIsInvalid)bmp.GetType().GetProperty("WicSourceHandle", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(bmp);
    var obj = Marshal.GetObjectForIUnknown(handle.DangerousGetHandle());
    return new WicBitmapSource(obj);
}
```
It uses a BitmapSource's private member field but since the WPF framework is frozen, I don't think it won't change ever and what's nice it's not using any memory because WPF's underlying technology is WIC already. Or you can use more standard (but less faster) CopyPixels like you do with MagickImage.

Speaking of MagickImage, you code doesn't work because you're not getting a byte array that matches the target 32bppPRGBA format. This should work:

```
using var imgM = new MagickImage("photo.png");
var bytes = imgM.ToByteArray(MagickFormat.Rgba); // for example
var stride = ((imgM.Width * 32 + 31) & ~31) / 8;
        
using var bmp = WicBitmapSource.FromMemory(
  imgM.Width,
  imgM.Height,
  WicPixelFormat.GUID_WICPixelFormat32bppPRGBA,
  stride,
  bytes);
```

**Comment by d2phap** [comment]
Thank you, it works!
